#!/bin/bash
# Update Discord


if [ $# -ne 2 ]; then
    echo "Usage: $0 <install or update> <path to discord>"
    exit 1
fi

DICORDLINK=$(curl -s -i -H "Accept: application/json" -H "Content-Type: application/json" -X GET https://discord.com/api/download\?platform\=linux\&format\=tar.gz)
RETURN=$?
DISCORDVERSION=$(echo "$DICORDLINK" | grep location | cut -d'/' -f 6)

if [ $RETURN -ne 0 ]; then
    echo "Error: $RETURN couldn't get Discord download link"
    exit 1
fi


if [ $1 = "install" ]; then
    echo "Installing Discord into $2"
    if [ -d $2 ]; then
        echo "Error: $2 already exists"
        exit 1
    fi
    mkdir -p $2
    cd $2
    wget -q -O discord.tar.gz "https://discord.com/api/download?platform=linux&format=tar.gz"
    RETURN=$?
    if [ $RETURN -ne 0 ]; then
        echo "Error: $RETURN couldn't download Discord"
        exit 1
    fi
    tar -xvzf discord.tar.gz > /dev/null
    rm discord.tar.gz > /dev/null
    ICONPATH=$(pwd)
    ICONPATH+="/Discord/discord.png"
    echo $DISCORDVERSION > version
    echo "Do you want to create a desktop entry? (y/n)"
    read -r answer
    if [ "$answer" != "${answer#[Yy]}" ] ;then
        if [ ! -d ~/.local/share/applications ]; then
            mkdir -p ~/.local/share/applications
        fi
        echo "Creating desktop entry"
        EXECPATH=$(pwd)
        EXECPATH+="/Discord/Discord"
        echo $EXECPATH
        echo "[Desktop Entry]
Encoding=UTF-8
Version=$DISCORDVERSION
Type=Application
Terminal=false
Exec=$EXECPATH
Name=Discord
Icon=$ICONPATH" > ~/.local/share/applications/discord.desktop
    update-desktop-database ~/.local/share/applications
    else
        echo "Not creating desktop entry"
    fi
    echo "Discord installed"
    exit 0
fi

if [ $1 = "update" ]; then
    echo "Updating Discord"
    cd $2
    if [ ! -f version ]; then
        echo "Error: version file not found"
        exit 1
    fi
    if [ $(cat version) = $DISCORDVERSION ]; then
        echo "Discord is up to date"
        exit 0
    fi
    rm -rf Discord > /dev/null
    wget -q -O discord.tar.gz "https://discord.com/api/download?platform=linux&format=tar.gz"
    RETURN=$?
    if [ $RETURN -ne 0 ]; then
        echo "Error: $RETURN couldn't download Discord"
        exit 1
    fi
    tar -xvzf discord.tar.gz > /dev/null
    rm discord.tar.gz > /dev/null
    echo $DISCORDVERSION > version
    echo "Discord updated"
    exit 0
fi
