#!/bin/bash

USAGE_NAME=$(basename $0)
if [ $# -eq 0 ]
then
	echo "Usage: $USAGE_NAME [project_name]"
	exit 1
fi

PROJECT_NAME=$1
##download zipball from git
wget https://github.com/GodlyJaaaj/shell_bash_scripts/zipball/init_repo_files -O $PROJECT_NAME.zip

if [ $? -ne 0 ]
then
  echo "Error: Could not download zipball from git"
  exit 1
fi

##unzip
unzip $PROJECT_NAME.zip
##remove zip
rm $PROJECT_NAME.zip
##move all files to current directory
mv GodlyJaaaj-shell_bash_scripts-*/* .
##remove empty directory
rmdir GodlyJaaaj-shell_bash_scripts-*/

./init.sh $PROJECT_NAME
rm init_my_repo